estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/garagem/')),
]

urlpatterns += [
    path('garagem/', include('garagem.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

garagem/urls.py
from django.urls import path
from garagem import views

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += [
    path('veiculos/', views.VehicleListView.as_view(), name='veiculos'),
    path('veiculos/<int:pk>', views.VehicleDetailView.as_view(), name='veiculo-detalhes'),
    path('veiculo/create/', views.VehicleCreate.as_view(), name='veiculo-create'),
    path('veiculo/<int:pk>/update/', views.VehicleUpdate.as_view(), name='veiculo-update'),
    path('veiculo/<int:pk>/delete/', views.VehicleDelete.as_view(), name='veiculo-delete'),
]

urlpatterns += [
    path('proprietarios/', views.OwnerListView.as_view(), name='proprietarios'),
    path('proprietarios/<int:pk>', views.OwnerDetailView.as_view(), name='proprietario-detalhes'),
    path('proprietario/create/', views.OwnerCreate.as_view(), name='proprietario-create'),
    path('proprietario/<int:pk>/update/', views.OwnerUpdate.as_view(), name='proprietario-update'),
    path('proprietario/<int:pk>/delete/', views.OwnerDelete.as_view(), name='proprietario-delete'),
]

urlpatterns += [
    path('vagas/', views.VagaListView.as_view(), name='vagas'),
    path('vagas/<int:pk>', views.VagaDetailView.as_view(), name='vaga-detalhes'),
    path('vaga/', views.VagaCreate.as_view(), name='vaga-create'),
    path('vaga/<int:pk>/update/', views.VagaUpdate.as_view(), name='vaga-update'),
    path('vaga/<int:pk>/delete/', views.VagaDelete.as_view(), name='vaga-delete'),
]

garagem/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Tipo(models.Model):
    nome = models.CharField(max_length=100, help_text='Entre com o tipo do veículo. Ex: Automóvel.')

    def __str__(self):
        return self.nome


class Proprietario(models.Model):
    primeiro_nome = models.CharField(max_length=100)
    ultimo_nome = models.CharField(max_length=100)
    data_nascimento = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['primeiro_nome','ultimo_nome']
        permissions = (("pode_manipular_proprietario", "Manipula o cadastro de proprietários."),)

    def get_absolute_url(self):
        return reverse('proprietario-detalhes', args=[str(self.id)])

    def __str__(self):
        return f'{self.primeiro_nome} {self.ultimo_nome}'


class Veiculo(models.Model):
    fabricante = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    tipo = models.ForeignKey(Tipo, on_delete=models.SET_NULL, null=True)
    cor = models.CharField(max_length=20, help_text='Entre com a cor predominante do veículo. Ex: Prata')
    proprietario = models.ForeignKey(Proprietario, on_delete=models.SET_NULL, null=True)


    class Meta:
        ordering = ['modelo']
        permissions = (("pode_manipular_veiculo", "Manipula o cadastro de veículos."),)

    def get_absolute_url(self):
        return reverse('veiculo-detalhes', args=[str(self.id)])

    def __str__(self):
        return f'{self.fabricante}/{self.modelo}'


from datetime import date

class Vaga(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.SET_NULL, null=True)
    data_retirada = models.DateField(null=True, blank=True)

    SITUACAO_VAGA = (
        ('o', 'Ocupada'),
        ('m', 'Manutenção'),
    )

    situacao = models.CharField(
        max_length=1,
        choices=SITUACAO_VAGA,
        blank=True,
        default='o',
        help_text='Situação da vaga',
    )

    def esta_atrasado(self):
        if self.data_retirada and date.today() > self.data_retirada:
            return True
        return False

    class Meta:
        ordering = ['data_retirada']
        permissions = (("pode_manipular_vaga", "Manipula o cadastro de vagas."),)

    def get_absolute_url(self):
        return reverse('vaga-detalhes', args=[str(self.id)])

    def __str__(self):
        return f'{self.id} ({self.veiculo})'

garagem/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

from garagem.models import Tipo, Proprietario, Veiculo, Vaga


def index(request):
    num_veiculos = Veiculo.objects.all().count()
    num_proprietarios = Proprietario.objects.all().count()
    num_tipos = Tipo.objects.all().count()

    num_vagas_ocupadas = Vaga.objects.filter(situacao__exact='o').count()
    num_vagas_manutencao = Vaga.objects.filter(situacao__exact='m').count()
    num_vagas = Vaga.objects.all().count()


    contexto = {
        'num_veiculos': num_veiculos,
        'num_proprietarios': num_proprietarios,
        'num_tipos': num_tipos,

        'num_vagas_ocupadas': num_vagas_ocupadas,
        'num_vagas_manutencao': num_vagas_manutencao,
        'num_vagas': num_vagas,

    }

    return render(request, 'index.html', context=contexto)


class VehicleListView(generic.ListView):
    model = Veiculo


class VehicleDetailView(generic.DetailView):
    model = Veiculo


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin


class VehicleCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'garagem.pode_manipular_veiculo'
    model = Veiculo
    fields = '__all__'


class VehicleUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'garagem.pode_manipular_veiculo'
    model = Veiculo
    fields = ['modelo', 'fabricante', 'cor', 'tipo']


class VehicleDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'garagem.pode_manipular_veiculo'
    model = Veiculo
    success_url = reverse_lazy('veiculos')


class OwnerListView(generic.ListView):
    model = Proprietario


class OwnerDetailView(generic.DetailView):
    model = Proprietario


class OwnerCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'garagem.pode_manipular_proprietario'
    model = Proprietario
    fields = '__all__'


class OwnerUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'garagem.pode_manipular_proprietario'
    model = Proprietario
    fields = '__all__'


class OwnerDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'garagem.pode_manipular_proprietario'
    model = Proprietario
    success_url = reverse_lazy('proprietarios')


class VagaListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'garagem.pode_manipular_vaga'
    model = Vaga

class VagaDetailView(generic.DetailView):
    permission_required = 'garagem.pode_manipular_vaga'
    model = Vaga

class VagaCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'garagem.pode_manipular_vaga'
    model = Vaga
    fields = ['veiculo', 'data_retirada']

class VagaUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'garagem.pode_manipular_vaga'
    model = Vaga
    fields = '__all__'

class VagaDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'garagem.pode_manipular_vaga'
    model = Vaga
    success_url = reverse_lazy('vagas')

garagem/templates/base_generic.html
<!doctype html>
<html lang="pt-br">
    <head>
        {% block title %}
            <title>Sistema de Gestão - Estacionamento</title>
        {% endblock %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


        {% load static %}
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        {% block sidebar %}
            <div class="sidebar-container">
                <div class="sidebar-logo">
                    Estacionamento
                </div>
                <ul class="sidebar-navigation">
                    <li class="header">VISÃO GERAL</li>
                    <li>
                        <a href="{% url 'index' %}">
                            <i class="fa fa-home" aria-hidden="true"></i> Página inicial
                        </a>
                    </li>
                    <li>
                        <a href="{%url 'veiculos'%}">
                            <i class="fa fa-home" aria-hidden="true"></i> Todos os veículos
                        </a>
                    </li>
                    <li>
                        <a href="{%url 'proprietarios'%}">
                            <i class="fa fa-home" aria-hidden="true"></i> Todos os proprietários
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                        <li class="user">User: {{ user.get_username }}</li>
                        {% if perms.garagem.pode_manipular_vaga %}
                            <li class="header">ADMINISTRADOR</li>
                            <li>
                                <a href="{% url 'vagas'%}">
                                        <i class="fa fa-users" aria-hidden="true"></i> Todas as vagas
                                </a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endblock %}

        <div class="content-container">
            <div class="container-fluid">
                <div class="jumbotron">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

garagem/templates/garagem/proprietario_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Apagar Proprietário</h1>

    <p>Tem certeza que quer excluir esse proprietário: {{ proprietario }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim, excluir.">
    </form>

{% endblock %}

garagem/templates/garagem/proprietario_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Proprietário: {{ proprietario.primeiro_nome }} {{ proprietario.ultimo_nome }}</h1>

    <p><strong>Nome: </strong>{{ proprietario.primeiro_nome }}</a></p>
    <p><strong>Sobrenome:</strong> {{ proprietario.ultimo_nome }}</p>
    <p><strong>Data de Nascimento:</strong> {{ proprietario.data_nascimento }}</p>

{% endblock %}

garagem/templates/garagem/proprietario_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

garagem/templates/garagem/proprietario_list.html
{% extends "base_generic.html"%}

{% block content %}

    <h1>Proprietários</h1>




    <div style="margin-bottom: 2%">
        {% if perms.garagem.pode_manipular_proprietario %}
            <a href="{% url 'proprietario-create' %}">
                <button type="button" class="btn btn-outline-dark">Novo proprietário</button>
            </a>
        {% endif %}
    </div>

    {% if proprietario_list %}
        {% for proprietario in proprietario_list %}
            <div class="card bg-light border-dark mb-3">
                <div class="card-header bg-transparent border-info mb-3">Data de Nascimento: {{proprietario.data_nascimento}}</div>
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ proprietario.get_absolute_url }}">{{proprietario.primeiro_nome}}</a></h5>
                    <p class="card-text">{{proprietario.ultimo_nome}}</p>
                </div>
                <div class="card-footer bg-transparent border-info mb-3">
                    {% if perms.garagem.pode_manipular_proprietario %}
                        <div>
                            <a href="{% url 'proprietario-update' proprietario.id%}" class="btn btn-primary" role="button">Atualizar</a>
                            <a href="{% url 'proprietario-delete' proprietario.id%}" class="btn btn-danger" role="button">Excluir</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <p>Não existem proprietários cadastrados.</p>
    {% endif %}

{% endblock %}

garagem/templates/garagem/vaga_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Apagar Vaga</h1>

    <p>Tem certeza que quer excluir essa vaga: {{ vaga }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim, excluir.">
    </form>

{% endblock %}

garagem/templates/garagem/vaga_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Vaga: {{ vaga.veiculo.modelo }} {{ vaga.situacao }}</h1>

    <p><strong>Modelo: </strong>{{ vaga.veiculo.modelo }}</a></p>
    <p><strong>Situação:</strong> {{ vaga.situacao }}</p>
    <p><strong>Data de Retirada:</strong> {{ vaga.data_retirada }}</p>

{% endblock %}

garagem/templates/garagem/vaga_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

garagem/templates/garagem/vaga_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Vagas</h1>


    <div style="margin-bottom: 2%">
        {% if perms.garagem.pode_manipular_vaga %}
            <a href="{% url 'vaga-create' %}">
                <button type="button" class="btn btn-outline-dark">Nova vaga</button>
            </a>
        {% endif %}
    </div>

    {% if vaga_list %}
        {% for vaga in vaga_list %}
            <div class="card bg-light border-dark mb-3">
                <div class="card-header bg-transparent border-info mb-3">Modelo: {{ vaga.veiculo.modelo }}</div>
                <div class="card-body">
                    <h5 class="card-title">Data da retirada: <a href="{{ vaga.get_absolute_url }}">{{vaga.data_retirada}}</a></h5>
                    <p class="card-text">Situação da vaga: {{vaga.situacao}}</p>
                </div>
                <div class="card-footer bg-transparent border-info mb-3">
                    {% if perms.garagem.pode_manipular_vaga %}
                        <div>
                            <a href="{% url 'vaga-update' vaga.id%}" class="btn btn-primary" role="button">Atualizar</a>
                            <a href="{% url 'vaga-delete' vaga.id%}" class="btn btn-danger" role="button">Excluir</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <p>Não há vagas ocupadas em nosso estacionamento.</p>
    {% endif %}




{% endblock %}

garagem/templates/garagem/veiculo_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Apagar Veículo</h1>

    <p>Tem certeza que quer excluir esse veículo: {{ veiculo }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim, excluir.">
    </form>

{% endblock %}

garagem/templates/garagem/veiculo_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Veículo: {{ veiculo.fabricante }}/{{ veiculo.modelo }}</h1>

    <p><strong>Modelo: </strong>{{ veiculo.modelo }}</a></p>
    <p><strong>Fabricante:</strong> {{ veiculo.fabricante }}</p>
    <p><strong>Proprietário:</strong> {{ veiculo.proprietario }}</p>
    <p><strong>Cor:</strong> {{ veiculo.cor }}</p>
    <p><strong>Tipo:</strong> {{ veiculo.tipo }}</p>

    <div style="margin-left: 20px;margin-top: 20px">
        <h4>Vaga</h4>
        {%for copy in veiculo.vaga_set.all%}
        <p class="{% if copy.situacao == 'o' %}text-success{% elif copy.situacao == m%}text-danger{% else %} text-warning{% endif %}">
            {{ copy.get_situacao_display }}</p>

        {% if copy.situacao != m %}
        <p><strong>Deve ser retirado em:</strong> {{copy.data_retirada}}</p>
        {% endif %}
        <p class="text-muted"><strong>Id:</strong>{{copy.id}}</p>
        {% endfor %}

    </div>



{% endblock %}

garagem/templates/garagem/veiculo_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

garagem/templates/garagem/veiculo_list.html
{% extends "base_generic.html"%}

{% block content %}


    <h1>Veículos</h1>

    <div style="margin-bottom: 2%">
        {% if perms.garagem.pode_manipular_veiculo %}
            <a href="{% url 'veiculo-create' %}">
                <button type="button" class="btn btn-outline-dark">Novo veículo</button>
            </a>
        {% endif %}
    </div>


    {% if veiculo_list %}
        {% for veiculo in veiculo_list %}
            <div class="card bg-light border-dark mb-3">
                <div class="card-header bg-transparent border-info mb-3">Fabricante: {{veiculo.fabricante}}</div>
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ veiculo.get_absolute_url }}">{{veiculo.modelo}}</a></h5>
                    <p class="card-text">Proprietário: {{veiculo.proprietario}}</p>
                </div>
                <div class="card-footer bg-transparent border-info mb-3">
                    {% if perms.garagem.pode_manipular_veiculo %}
                        <div>
                            <a href="{% url 'veiculo-update' veiculo.id%}" class="btn btn-primary" role="button">Atualizar</a>
                            <a href="{% url 'veiculo-delete' veiculo.id%}" class="btn btn-danger" role="button">Excluir</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <p>Não existem veículos no estacionamento.</p>
    {% endif %}

{% endblock %}

garagem/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Página inicial</h1>


    <h2>Sistema de Gestão</h2>

    <div class="card border-dark mb-3">
        <div class="card-header bg-transparent">O estacionamento tem atualmente os seguintes registros:</div>
        <div class="card-body">
            <h5 class="card-title">Visão geral</h5>
            <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item justify-content-between align-items-center"><strong>Veículos:</strong> {{ num_veiculos }}</li>
                    <li class="list-group-item justify-content-between align-items-center"><strong>Proprietários:</strong> {{ num_proprietarios }}</li>
                    <li class="list-group-item justify-content-between align-items-center"><strong>Tipos de veículos:</strong> {{ num_tipos }}</li>
                    <li class="list-group-item justify-content-between align-items-center"><strong>Vagas que estão ocupadas:</strong> {{ num_vagas_ocupadas }}</li>
                    <li class="list-group-item justify-content-between align-items-center"><strong>Vagas que precisam de manutenção:</strong> {{ num_vagas_manutencao }}</li>
                    <li class="list-group-item justify-content-between align-items-center"><strong>Total de vagas:</strong> {{ num_vagas }}</li>
                </ul>
            </p>
        </div>
        <div class="card-footer bg-transparent"><strong>ESTACIONAMENTO</strong></div>
    </div>

{% endblock %}